---
- name: Fail if shelly_gen is not 1 or 2
  ansible.builtin.fail:
    msg: "shell_gen is not 1 or 2"
  when:
    - shelly_gen != 1
    - shelly_gen != 2

- name: Include Shelly tasks for Gen {{ shelly_gen }}
  ansible.builtin.include_tasks:
    file: "gen{{ shelly_gen }}.yml"

- name: Include tasks to update Shelly
  ansible.builtin.include_tasks:
    file: update.yml
  when: shelly_update | bool
