---
- name: Set configuration
  ansible.builtin.command:
    cmd: 'curl -s {{ shelly_curl_auth }} -X POST -d ''{{ shelly_rpc_set_config_combined | to_json }}'' {{ shelly_rpc_uri }}'
  no_log: true
  when: shelly_rpc_set_config | length > 0

- name: Get Status
  ansible.builtin.command:
    cmd: 'curl -s {{ shelly_curl_auth }} -X POST -d ''{{ shelly_rpc_get_status | to_json }}'' {{ shelly_rpc_uri }}'
  changed_when: false
  check_mode: false
  no_log: true
  register: __curl_get_status

- name: Convert curl Get Status output to JSON
  ansible.builtin.set_fact:
    __get_status: "{{ __curl_get_status.stdout | from_json }}"

- name: Restart if required
  ansible.builtin.command:
    cmd: 'curl -s {{ shelly_curl_auth }} -X POST -d ''{{ shelly_rpc_reboot | to_json }}'' {{ shelly_rpc_uri }}'
  when:
    - __get_status.result.restart_required | bool
    - shelly_restart | bool
