---
- name: Fail if shelly_gen is not 1 or 2
  ansible.builtin.fail:
    msg: "shell_gen is not 1 or 2"
  when:
    - shelly_gen != 1
    - shelly_gen != 2
  tags: crap

- name: Include Shelly tasks for Gen {{ shelly_gen }}
  ansible.builtin.include_tasks:
    file: "gen{{ shelly_gen }}.yml"
